# Generated by Django 5.0.1 on 2025-03-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
    ]
