# Generated by Django 5.0.1 on 2025-03-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
