# Generated by Django 5.0.1 on 2025-03-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0004_rename_services_carhistory_service'),
        ('management', '0003_alter_notification_options_alter_notification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientdata.car'),
        ),
    ]
