# Generated by Django 5.0.1 on 2025-03-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_notification_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='car_kms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
