# Generated by Django 5.0.1 on 2025-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_notification_car_kms'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notificated',
            field=models.BooleanField(default=False),
        ),
    ]
