# Generated by Django 5.0.1 on 2025-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_notification_notificated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificated',
            field=models.BooleanField(),
        ),
    ]
