# Generated by Django 5.0.1 on 2025-03-04 21:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0004_rename_services_carhistory_service'),
        ('projects', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientdata.car'),
        ),
        migrations.AddField(
            model_name='project',
            name='car_kms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 22, 57, 39, 421057)),
        ),
    ]
