# Generated by Django 5.0.1 on 2025-03-08 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_comment_created_at_alter_project_car_kms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 15, 15, 35, 390745)),
        ),
    ]
