# Generated by Django 5.0.1 on 2025-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
