# Generated by Django 5.0.1 on 2025-03-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0002_alter_car_last_service_date'),
        ('projects', '0003_alter_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientdata.car')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Car History',
                'verbose_name_plural': 'Car Histories',
                'db_table': 'car_history',
                'ordering': ['-id'],
            },
        ),
    ]
